name: CI

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: WHO ARE YOU
        run: echo "Push $GITHUB_ACTOR"

      # Runs a set of commands using the runners shell
      - name: ACTION-SLACK
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "잡았다 요놈"
          fields: repo,message,commit,author,eventName
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
